// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRdHqKDJBSPVvvcPyQB0XgrUHIZyK5SkY',
    appId: '1:917621993016:web:9f01a1fc7bc8e7f48d80cd',
    messagingSenderId: '917621993016',
    projectId: 'take-my-time-faa13',
    authDomain: 'take-my-time-faa13.firebaseapp.com',
    storageBucket: 'take-my-time-faa13.appspot.com',
    measurementId: 'G-N2V3K2K7KY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-xdZBOMSzGcloGFkzEnfo2nosIrSf8sU',
    appId: '1:917621993016:android:fb5c29f4f273df948d80cd',
    messagingSenderId: '917621993016',
    projectId: 'take-my-time-faa13',
    storageBucket: 'take-my-time-faa13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5LPAA4AabDWyjwiSrsSB3NySxzfEnWCE',
    appId: '1:917621993016:ios:ec33797202643f918d80cd',
    messagingSenderId: '917621993016',
    projectId: 'take-my-time-faa13',
    storageBucket: 'take-my-time-faa13.appspot.com',
    iosBundleId: 'com.example.secondProject',
  );
}
